name: sanitizers

on: [push, pull_request]

jobs:
  address:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rauc/rauc/rauc-ci:latest
      # allow mounting and devtmpfs in the container
      options: --user=root --privileged -v /dev:/dev
    steps:
    - name: Inspect environment
      run: |
        whoami
        gcc --version
        ls -l /dev/kvm || true

    - uses: actions/checkout@v4

    - name: Run meson
      run: |
        meson setup build -Db_sanitize=address
        meson configure build
        meson compile -C build

    - name: Run tests
      run: |
        ./qemu-test asan

    - name: Show logs
      if: ${{ failure() }}
      run: |
        cat build/meson-logs/testlog.txt || true
